version: "3.7"

services:
    app:
        image: speaker-ident:v1
        container_name: speaker-ident
        ports:
            - "5000:5000"
        # restart: always
        volumes:
            - ./:/app
        environment:
            FLASK_DEBUG: 1